In [15]:
import pandas as pd
import numpy as py

In [16]:
#Load dataset
df = pd.read_csv('/content/drive/MyDrive/ColabNotebooks/titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,\N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,\N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,\N,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13.0000,\N,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,\N,1,2,W./C. 6607,23.4500,\N,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.7500,\N,Q

In [17]:
#previewing the first five rows to what my tables entails
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,\N,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,\N,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,\N,S

In [18]:
#Previewing the bottom rows
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27,0,0,211536,13.00,\N,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,\N,1,2,W./C. 6607,23.45,\N,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32,0,0,370376,7.75,\N,Q

In [19]:
#This is used to know the number of rows and columns

df.shape

(891, 12)

In [20]:
#This is used to get every info about your dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    object
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object
 11  Embarked     891 non-null    object
dtypes: float64(1), int64(5), object(6)
memory usage: 83.7+ KB

In [22]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    object
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object
 11  Embarked     891 non-null    object
dtypes: float64(1), int64(5), object(6)
memory usage: 83.7+ KB

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [23]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    object
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        891 non-null    object
 11  Embarked     891 non-null    object
dtypes: float64(1), int64(5), object(6)
memory usage: 83.7+ KB

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [32]:
#checking the unique value in the column

print(df['Embarked'].unique())
print(df['Pclass'].unique())
print(df['Age'].unique())
print(df['Cabin'].unique())

['S' 'C' 'Q' '\\N']
[3 1 2]
[22 38 26 35 29 54  2 27 14  4 58 20 39 55 31 34 15 28  8 19 40 66 42 21
 18  3  7 49 65  5 11 45 17 32 16 25  0 30 33 23 24 46 59 71 37 47 70 12
  9 36 51 44  1 61 56 50 62 41 52 63 43 60 10 64 13 48 53 57 80  6 74]
[nan 'C85' 'C123' 'E46' 'G6' 'C103' 'D56' 'A6' 'C23 C25 C27' 'B78' 'D33'
 'B30' 'C52' 'B28' 'C83' 'F33' 'F G73' 'E31' 'A5' 'D10 D12' 'D26' 'C110'
 'B58 B60' 'E101' 'F E69' 'D47' 'B86' 'F2' 'C2' 'E33' 'B19' 'A7' 'C49'
 'F4' 'A32' 'B4' 'B80' 'A31' 'D36' 'D15' 'C93' 'C78' 'D35' 'C87' 'B77'
 'E67' 'B94' 'C125' 'C99' 'C118' 'D7' 'A19' 'B49' 'D' 'C22 C26' 'C106'
 'C65' 'E36' 'C54' 'B57 B59 B63 B66' 'C7' 'E34' 'C32' 'B18' 'C124' 'C91'
 'E40' 'T' 'C128' 'D37' 'B35' 'E50' 'C82' 'B96 B98' 'E10' 'E44' 'A34'
 'C104' 'C111' 'C92' 'E38' 'D21' 'E12' 'E63' 'A14' 'B37' 'C30' 'D20' 'B79'
 'E25' 'D46' 'B73' 'C95' 'B38' 'B39' 'B22' 'C86' 'C70' 'A16' 'C101' 'C68'
 'A10' 'E68' 'B41' 'A20' 'D19' 'D50' 'D9' 'A23' 'B50' 'A26' 'D48' 'E58'
 'C126' 'B71' 'B51 B53 B55' 'D49' 'B5' 'B20' 'F G63' 'C62 C64' 'E24' 'C90'
 'C45' 'E8' 'B101' 'D45' 'C46' 'D30' 'E121' 'D11' 'E77' 'F38' 'B3' 'D6'
 'B82 B84' 'D17' 'A36' 'B102' 'B69' 'E49' 'C47' 'D28' 'E17' 'A24' 'C50'
 'B42' 'C148']

In [35]:
import numpy as np
df['Cabin'] = df['Cabin'].replace('\\N', np.nan)
print(df['Cabin'].unique())
print(df['Embarked'].unique())
df.head()

[nan 'C85' 'C123' 'E46' 'G6' 'C103' 'D56' 'A6' 'C23 C25 C27' 'B78' 'D33'
 'B30' 'C52' 'B28' 'C83' 'F33' 'F G73' 'E31' 'A5' 'D10 D12' 'D26' 'C110'
 'B58 B60' 'E101' 'F E69' 'D47' 'B86' 'F2' 'C2' 'E33' 'B19' 'A7' 'C49'
 'F4' 'A32' 'B4' 'B80' 'A31' 'D36' 'D15' 'C93' 'C78' 'D35' 'C87' 'B77'
 'E67' 'B94' 'C125' 'C99' 'C118' 'D7' 'A19' 'B49' 'D' 'C22 C26' 'C106'
 'C65' 'E36' 'C54' 'B57 B59 B63 B66' 'C7' 'E34' 'C32' 'B18' 'C124' 'C91'
 'E40' 'T' 'C128' 'D37' 'B35' 'E50' 'C82' 'B96 B98' 'E10' 'E44' 'A34'
 'C104' 'C111' 'C92' 'E38' 'D21' 'E12' 'E63' 'A14' 'B37' 'C30' 'D20' 'B79'
 'E25' 'D46' 'B73' 'C95' 'B38' 'B39' 'B22' 'C86' 'C70' 'A16' 'C101' 'C68'
 'A10' 'E68' 'B41' 'A20' 'D19' 'D50' 'D9' 'A23' 'B50' 'A26' 'D48' 'E58'
 'C126' 'B71' 'B51 B53 B55' 'D49' 'B5' 'B20' 'F G63' 'C62 C64' 'E24' 'C90'
 'C45' 'E8' 'B101' 'D45' 'C46' 'D30' 'E121' 'D11' 'E77' 'F38' 'B3' 'D6'
 'B82 B84' 'D17' 'A36' 'B102' 'B69' 'E49' 'C47' 'D28' 'E17' 'A24' 'C50'
 'B42' 'C148']
['S' 'C' 'Q' nan]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

In [34]:
# Replace '\N' strings with NaN
df['Embarked'] = df['Embarked'].replace('\\N', np.nan)

# Replace '\N' strings with NaN
df['Age'] = df['Age'].replace('\\N', np.nan)

# Convert to numeric, coercing errors to NaN
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')

# Fill NaN values with the mean of the 'Age' column
df['Age'] = df['Age'].fillna(df['Age'].mean())

# Convert to integer type
df['Age'] = df['Age'].astype(int)

print(df['Age'].dtype)
df.head()

int64

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    int64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     891 non-null    object
dtypes: float64(1), int64(6), object(5)
memory usage: 83.7+ KB

In [30]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.544332,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,13.013778,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,22.000000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,29.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,35.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [37]:
##Checking for duplicate

duplicate_rows = df[df.duplicated()]
print("Duplicate Rows:")
print(duplicate_rows)

Duplicate Rows:
Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

Result:
No duplicate found in all the rows

In [41]:
## Renamed all columns to lowercase and removed all space in the column name.

df.columns = df.columns.str.lower().str.replace(' ', '')
df.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,NaN,S

In [42]:
## Identified all strings column in my table

object_columns = df.select_dtypes(include='object').columns.tolist()
print("Columns with object data type:", object_columns)

Columns with object data type: ['name', 'sex', 'ticket', 'cabin', 'embarked']

In [43]:
## converted all Strings column text value to lowercase and removed all space
for col in object_columns:
    if df[col].dtype == 'object':
        df[col] = df[col].astype(str).str.strip().str.lower()

df.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,0,3,"braund, mr. owen harris",male,22,1,0,a/5 21171,7.2500,nan,s
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",female,38,1,0,pc 17599,71.2833,c85,c
2,3,1,3,"heikkinen, miss. laina",female,26,0,0,ston/o2. 3101282,7.9250,nan,s
3,4,1,1,"futrelle, mrs. jacques heath (lily may peel)",female,35,1,0,113803,53.1000,c123,s
4,5,0,3,"allen, mr. william henry",male,35,0,0,373450,8.0500,nan,s

In [44]:
#created a new deck column by exctracting the first initials from the cabin column

df['deck'] = df['cabin'].apply(lambda x: x[0] if pd.notna(x) and x != 'nan' else np.nan)
df.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,deck
0,1,0,3,"braund, mr. owen harris",male,22,1,0,a/5 21171,7.2500,nan,s,NaN
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",female,38,1,0,pc 17599,71.2833,c85,c,c
2,3,1,3,"heikkinen, miss. laina",female,26,0,0,ston/o2. 3101282,7.9250,nan,s,NaN
3,4,1,1,"futrelle, mrs. jacques heath (lily may peel)",female,35,1,0,113803,53.1000,c123,s,c
4,5,0,3,"allen, mr. william henry",male,35,0,0,373450,8.0500,nan,s,NaN

In [45]:
## Replaced all Nan in Embarked colum with the mode of the Embarked column

df['embarked'] = df['embarked'].replace('nan', np.nan)
mode_embarked = df['embarked'].mode()[0]
df['embarked'] = df['embarked'].fillna(mode_embarked)
df.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,deck
0,1,0,3,"braund, mr. owen harris",male,22,1,0,a/5 21171,7.2500,nan,s,NaN
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",female,38,1,0,pc 17599,71.2833,c85,c,c
2,3,1,3,"heikkinen, miss. laina",female,26,0,0,ston/o2. 3101282,7.9250,nan,s,NaN
3,4,1,1,"futrelle, mrs. jacques heath (lily may peel)",female,35,1,0,113803,53.1000,c123,s,c
4,5,0,3,"allen, mr. william henry",male,35,0,0,373450,8.0500,nan,s,NaN

In [59]:
## created  a new agegroup column

bins = [0, 12, 20, 60, df['age'].max()]
labels = ['Child', 'Teen', 'Adult', 'Senior']
df['agegroup'] = pd.cut(df['age'], bins=bins, labels=labels, right=True)

df.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,deck,agegroup
0,1,0,3,"braund, mr. owen harris",male,22,1,0,a/5 21171,7.2500,nan,s,NaN,Adult
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",female,38,1,0,pc 17599,71.2833,c85,c,c,Adult
2,3,1,3,"heikkinen, miss. laina",female,26,0,0,ston/o2. 3101282,7.9250,nan,s,NaN,Adult
3,4,1,1,"futrelle, mrs. jacques heath (lily may peel)",female,35,1,0,113803,53.1000,c123,s,c,Adult
4,5,0,3,"allen, mr. william henry",male,35,0,0,373450,8.0500,nan,s,NaN,Adult

In [61]:
## created the passengertitle column from the name column by the regular expression module
import re

def extract_title(name):
    title_search = re.search(r'([a-z]+)\.', name)
    if title_search:
        title = title_search.group(1)
        if title in ['mr', 'mrs', 'miss']:
            return title
    return 'other'

df['passengertitle'] = df['name'].apply(extract_title)
df.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,deck,agegroup,passengertitle
0,1,0,3,"braund, mr. owen harris",male,22,1,0,a/5 21171,7.2500,nan,s,NaN,Adult,mr
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",female,38,1,0,pc 17599,71.2833,c85,c,c,Adult,mrs
2,3,1,3,"heikkinen, miss. laina",female,26,0,0,ston/o2. 3101282,7.9250,nan,s,NaN,Adult,miss
3,4,1,1,"futrelle, mrs. jacques heath (lily may peel)",female,35,1,0,113803,53.1000,c123,s,c,Adult,mrs
4,5,0,3,"allen, mr. william henry",male,35,0,0,373450,8.0500,nan,s,NaN,Adult,mr

In [62]:
df['familysize'] = df['sibsp'] + df['parch'] + 1
df.head()

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,deck,agegroup,passengertitle,familysize
0,1,0,3,"braund, mr. owen harris",male,22,1,0,a/5 21171,7.2500,nan,s,NaN,Adult,mr,2
1,2,1,1,"cumings, mrs. john bradley (florence briggs th...",female,38,1,0,pc 17599,71.2833,c85,c,c,Adult,mrs,2
2,3,1,3,"heikkinen, miss. laina",female,26,0,0,ston/o2. 3101282,7.9250,nan,s,NaN,Adult,miss,1
3,4,1,1,"futrelle, mrs. jacques heath (lily may peel)",female,35,1,0,113803,53.1000,c123,s,c,Adult,mrs,2
4,5,0,3,"allen, mr. william henry",male,35,0,0,373450,8.0500,nan,s,NaN,Adult,mr,1

In [63]:
# Export the DataFrame to a CSV file
output_csv_path = 'cleaned_titanic_data.csv'
df.to_csv(output_csv_path, index=False)

print(f"Data exported to {output_csv_path}")

Data exported to cleaned_titanic_data.csv